language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: OwO77AeSSpOxzr3Fs66xl4x5OGSHKxMAxXuqiEfYiRgwHReQ3XgYtS5Xz5IPXDE0neNpEd2368Rt40iiFCWpKKiq0VzyWWKYNDuOLZYsDZQm2nB1IvqdY8LEIN3hLruAPhPGP0mSXPgPu0kp3IUzwoKxzYfDy4FKt1bllJPF9BZ7wyPq310B6qZ6POMZDG+yU3bvNaCpPiPSfA0iYkXV4UaOs8Y7cTwBFgCJhTVC7+TJuniQURujgTnoKHh9rra7LTT0g2vhaPCcLcs44nHKVLI1DekRVVTLDW8jgoR/0DLI8l+KXK54pW/HG+lpB0lG2FE0i1lxQOgu4rgqJ+jY7rFf5ORUaquMq/0DkqFwZjyS9hf397Wwa5OnPYagQMA63+n8ZzugVKPxtoqsekB9IkTvOq0ZCyD8uXFzsTI5lpasIWChhqoCurPQTGz11hXeACz66V+c9NaTebKszfVwUx4NDDUqa/oieqYKgTCrI4xmEQyXkhHNiUB2zt91gXcLNFI2UC1hsOCgf2Ku0ZqCpsfNGOM9gzXI2HcXlJTUgJkndfOX8uiaDwCw9BYl9/GsGFr3kIN0M3g1fUa+QTjFhhlyq95mfh2EmkCyp8ViCasfqvmSQDTMurTUKFfhV7MmLj3XZnU6wKOfDuhebpquG3C9070L4PfNwaBViOnmOUw=
  app: awesome-viewing_party
  run: rails db:migrate
  on: 
    branch: main
